ALTER TABLE profile
    ADD COLUMN IF NOT EXISTS handle VARCHAR(80),
    ADD COLUMN IF NOT EXISTS banner_url VARCHAR(255),
    ADD COLUMN IF NOT EXISTS cta_primary VARCHAR(120),
    ADD COLUMN IF NOT EXISTS cta_secondary VARCHAR(120),
    ADD COLUMN IF NOT EXISTS cta_tertiary VARCHAR(120);

